dbt_transformation:
  outputs:
    dev:
      type: snowflake
      account: ptxeavh-el73711

      # User/password auth
      user: Mustafa
      password: "@22Mustafa"

      role: ACCOUNTADMIN
      database: BIG_STAR_DATABASE
      warehouse: COMPUTE_WH
      schema: RAW_DATA
      threads: 1
      client_session_keep_alive: False
      query_tag:
  target: dev
